spring:
  application:
    name: proyecto1
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

  datasource:
    url: jdbc:mysql://mysql_test:3306/Interfaces
    username: root
    password: docker2
    # url: jdbc:mysql://localhost:3306/Interfaces
    # username: root
    # password: flavio2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



springdoc:
  swagger-ui:
    path: /swagger.html


my.key.private: jaA0eUlWaOse2CuBBSLscdumyBJBt6Em7wCGWtwkfMY
my.user.private: Auth




