version: '3.8'

services:
  mysql:
      image: mysql:latest
      container_name: mysql_test
      environment:
        MYSQL_ROOT_PASSWORD: 'docker2'
        MYSQL_DATABASE: Interfaces
        MYSQL_USER: flavio
        MYSQL_PASSWORD: 'docker2'
      ports:
        - '3308:3306'
      networks:
        - spring-network
      volumes:
        - mysql-data:/var/lib/mysql

  spring-api-image:
    image: spring-saavedra  # Usa la imagen de tu aplicación Spring Boot
    container_name: spring-api-container
    ports:
      - "8080:8080"  # Mapea el puerto 8080 del contenedor al 8080 del host
    networks:
      - spring-network
    depends_on:
      - mysql

networks:
  spring-network:

volumes:
  mysql-data: