version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 'docker2'
      MYSQL_DATABASE: Interfaces
      MYSQL_USER: flavio
      MYSQL_PASSWORD: 'docker2'
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:

networks:
  spring-network: